module.exports = {
  apps: [
    {
      name: "gmail-watcher",
      script: "watchers/gmail_watcher.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "200M",
      error_file: ".pm2/logs/gmail-watcher-error.log",
      out_file: ".pm2/logs/gmail-watcher-out.log",
      log_file: ".pm2/logs/gmail-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "whatsapp-watcher",
      script: "watchers/whatsapp_persistent.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "300M",
      error_file: ".pm2/logs/whatsapp-watcher-error.log",
      out_file: ".pm2/logs/whatsapp-watcher-out.log",
      log_file: ".pm2/logs/whatsapp-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "linkedin-watcher",
      script: "watchers/linkedin_persistent.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "300M",
      error_file: ".pm2/logs/linkedin-watcher-error.log",
      out_file: ".pm2/logs/linkedin-watcher-out.log",
      log_file: ".pm2/logs/linkedin-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "instagram-watcher",
      script: "watchers/instagram_watcher_fixed.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "300M",
      error_file: ".pm2/logs/instagram-watcher-error.log",
      out_file: ".pm2/logs/instagram-watcher-out.log",
      log_file: ".pm2/logs/instagram-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "facebook-watcher",
      script: "watchers/facebook_watcher_js_extract.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "300M",
      error_file: ".pm2/logs/facebook-watcher-error.log",
      out_file: ".pm2/logs/facebook-watcher-out.log",
      log_file: ".pm2/logs/facebook-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "twitter-watcher",
      script: "watchers/twitter_watcher.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "300M",
      error_file: ".pm2/logs/twitter-watcher-error.log",
      out_file: ".pm2/logs/twitter-watcher-out.log",
      log_file: ".pm2/logs/twitter-watcher-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "task-scheduler",
      script: "scheduler.py",
      interpreter: "python",
      watch: false,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "30s",
      max_memory_restart: "150M",
      error_file: ".pm2/logs/task-scheduler-error.log",
      out_file: ".pm2/logs/task-scheduler-out.log",
      log_file: ".pm2/logs/task-scheduler-combined.log",
      time: true,
      merge_logs: true,
    },
  ],
};
