#!/usr/bin/env python3
"""
Odoo ↔ Obsidian Synchronization
Syncs financial data from Odoo to Dashboard.md for real-time visibility.
Runs daily at 6 AM via scheduler.
"""

import requests
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("OdooSync")


class OdooSync:
    def __init__(self, odoo_url: str, vault_path: Path = None):
        self.odoo_url = odoo_url
        self.vault_path = vault_path or Path.cwd()
        self.dashboard_path = self.vault_path / "Dashboard.md"
        self.accounting_dir = self.vault_path / "Accounting"
        self.accounting_dir.mkdir(exist_ok=True)

    def get_financial_summary(self) -> Dict:
        """Get financial data from Odoo."""
        try:
            response = requests.get(f"{self.odoo_url}/summary", timeout=10)
            return response.json()
        except Exception as e:
            logger.error(f"Failed to fetch Odoo summary: {e}")
            return {}

    def get_unpaid_invoices(self) -> List[Dict]:
        """Get unpaid invoices from Odoo."""
        try:
            response = requests.get(f"{self.odoo_url}/invoices/unpaid", timeout=10)
            data = response.json()
            return data.get("unpaid_invoices", [])
        except Exception as e:
            logger.error(f"Failed to fetch unpaid invoices: {e}")
            return []

    def update_dashboard(self, summary: Dict, unpaid: List[Dict]):
        """Update Dashboard.md with latest financial data."""
        if not self.dashboard_path.exists():
            logger.warning("Dashboard.md not found, creating...")
            self.dashboard_path.write_text("# Dashboard\n\n## Financial Status\n\n")

        content = self.dashboard_path.read_text()

        # Update financial section
        financial_section = f"""## 💰 Financial Status
**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

### Revenue
- **Total Invoices:** {summary.get('total_invoices', 0)}
- **Total Revenue:** ${summary.get('total_revenue', 0):,.2f}
- **Unpaid Amount:** ${sum(inv.get('amount_total', 0) for inv in unpaid):,.2f}
- **Unpaid Count:** {len(unpaid)}

### Outstanding Invoices
"""

        for invoice in unpaid[:10]:  # Show top 10
            customer = invoice.get('partner_id', ['Unknown'])[1] if invoice.get('partner_id') else 'Unknown'
            amount = invoice.get('amount_total', 0)
            inv_date = invoice.get('invoice_date', '')
            financial_section += f"- {customer}: ${amount:,.2f} (since {inv_date})\n"

        if len(unpaid) > 10:
            financial_section += f"- ... and {len(unpaid) - 10} more\n"

        # Replace or insert financial section
        if "## 💰 Financial Status" in content:
            # Replace existing section
            start = content.find("## 💰 Financial Status")
            end = content.find("\n## ", start + 1)
            if end == -1:
                end = len(content)
            content = content[:start] + financial_section + content[end:]
        else:
            # Add new section
            content += "\n" + financial_section

        self.dashboard_path.write_text(content)
        logger.info("✓ Dashboard updated with latest financial data")

    def generate_monthly_summary(self):
        """Generate monthly summary for accounting."""
        today = datetime.now()
        month_start = today.replace(day=1)
        month_file = self.accounting_dir / f"Monthly_Summary_{today.strftime('%Y-%m')}.md"

        summary = self.get_financial_summary()
        unpaid = self.get_unpaid_invoices()

        content = f"""---
month: {today.strftime('%Y-%m')}
generated: {datetime.now().isoformat()}
---

# Monthly Summary: {today.strftime('%B %Y')}

## Revenue
- Total Invoices: {summary.get('total_invoices', 0)}
- Total Revenue: ${summary.get('total_revenue', 0):,.2f}
- Unpaid: ${sum(inv.get('amount_total', 0) for inv in unpaid):,.2f}

## Outstanding Items
Count: {len(unpaid)}

### By Customer
"""

        # Group by customer
        by_customer = {}
        for invoice in unpaid:
            customer = invoice.get('partner_id', ['Unknown'])[1] if invoice.get('partner_id') else 'Unknown'
            if customer not in by_customer:
                by_customer[customer] = 0
            by_customer[customer] += invoice.get('amount_total', 0)

        for customer, total in sorted(by_customer.items(), key=lambda x: x[1], reverse=True):
            content += f"- {customer}: ${total:,.2f}\n"

        content += f"\n## Next Actions\n- Follow up on overdue invoices\n- Generate collection notices\n\n"
        content += f"*Generated by Odoo Sync on {datetime.now().isoformat()}*"

        month_file.write_text(content)
        logger.info(f"✓ Monthly summary created: {month_file.name}")

    def sync(self):
        """Run full sync."""
        logger.info("Starting Odoo ↔ Obsidian sync...")

        # Get data from Odoo
        summary = self.get_financial_summary()
        unpaid = self.get_unpaid_invoices()

        if not summary and not unpaid:
            logger.warning("No data retrieved from Odoo")
            return False

        # Update local files
        self.update_dashboard(summary, unpaid)
        self.generate_monthly_summary()

        logger.info("✓ Sync completed successfully")
        return True


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Odoo ↔ Obsidian Sync")
    parser.add_argument("--odoo-url", default="http://localhost:3001", help="Odoo MCP URL")
    args = parser.parse_args()

    syncer = OdooSync(args.odoo_url)
    syncer.sync()


if __name__ == "__main__":
    main()
